# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:\School project(dms,sdoop)\book_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_book_form(object):
    def setupUi(self, book_form):
        book_form.setObjectName("book_form")
        book_form.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(book_form.sizePolicy().hasHeightForWidth())
        book_form.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(book_form)
        self.centralwidget.setObjectName("centralwidget")
        self.book_form_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.book_form_confirm.setGeometry(QtCore.QRect(140, 340, 151, 41))
        self.book_form_confirm.setObjectName("book_form_confirm")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.isbn_input = QtWidgets.QLineEdit(self.centralwidget)
        self.isbn_input.setGeometry(QtCore.QRect(140, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.isbn_input.setFont(font)
        self.isbn_input.setObjectName("isbn_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 159, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.auth_fname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.auth_fname_input.setGeometry(QtCore.QRect(140, 160, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auth_fname_input.setFont(font)
        self.auth_fname_input.setObjectName("auth_fname_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.book_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.book_name_input.setGeometry(QtCore.QRect(470, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.book_name_input.setFont(font)
        self.book_name_input.setText("")
        self.book_name_input.setObjectName("book_name_input")
        self.book_form_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.book_form_cancel.setGeometry(QtCore.QRect(400, 340, 151, 41))
        self.book_form_cancel.setObjectName("book_form_cancel")
        self.auth_lname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.auth_lname_input.setGeometry(QtCore.QRect(470, 161, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auth_lname_input.setFont(font)
        self.auth_lname_input.setText("")
        self.auth_lname_input.setObjectName("auth_lname_input")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        book_form.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(book_form)
        self.statusbar.setObjectName("statusbar")
        book_form.setStatusBar(self.statusbar)

        self.retranslateUi(book_form)
        QtCore.QMetaObject.connectSlotsByName(book_form)

    def retranslateUi(self, book_form):
        _translate = QtCore.QCoreApplication.translate
        book_form.setWindowTitle(_translate("book_form", "MainWindow"))
        self.book_form_confirm.setText(_translate("book_form", "Confirm"))
        self.label.setText(_translate("book_form", "ISBN"))
        self.label_2.setText(_translate("book_form", "Author First Name"))
        self.label_3.setText(_translate("book_form", "Book Name"))
        self.book_form_cancel.setText(_translate("book_form", "Cancel"))
        self.label_4.setText(_translate("book_form", "Author Last Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    book_form = QtWidgets.QMainWindow()
    ui = Ui_book_form()
    ui.setupUi(book_form)
    book_form.show()
    sys.exit(app.exec_())
