# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:\School project(dms,sdoop)\user_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_user_form(object):
    def setupUi(self, user_form):
        user_form.setObjectName("user_form")
        user_form.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(user_form)
        self.centralwidget.setObjectName("centralwidget")
        self.user_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.user_phone.setGeometry(QtCore.QRect(160, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_phone.setFont(font)
        self.user_phone.setObjectName("user_phone")
        self.user_form_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.user_form_cancel.setGeometry(QtCore.QRect(420, 330, 151, 41))
        self.user_form_cancel.setObjectName("user_form_cancel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(366, 48, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.user_lname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.user_lname_input.setGeometry(QtCore.QRect(498, 49, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_lname_input.setFont(font)
        self.user_lname_input.setObjectName("user_lname_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.user_form_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.user_form_confirm.setGeometry(QtCore.QRect(180, 330, 151, 41))
        self.user_form_confirm.setObjectName("user_form_confirm")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 49, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.user_fname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.user_fname_input.setGeometry(QtCore.QRect(160, 50, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_fname_input.setFont(font)
        self.user_fname_input.setObjectName("user_fname_input")
        user_form.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(user_form)
        self.statusbar.setObjectName("statusbar")
        user_form.setStatusBar(self.statusbar)

        self.retranslateUi(user_form)
        QtCore.QMetaObject.connectSlotsByName(user_form)

    def retranslateUi(self, user_form):
        _translate = QtCore.QCoreApplication.translate
        user_form.setWindowTitle(_translate("user_form", "MainWindow"))
        self.user_form_cancel.setText(_translate("user_form", "Cancel"))
        self.label_3.setText(_translate("user_form", "Last Name"))
        self.label_2.setText(_translate("user_form", "Phone No"))
        self.user_form_confirm.setText(_translate("user_form", "Confirm"))
        self.label.setText(_translate("user_form", "First Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    user_form = QtWidgets.QMainWindow()
    ui = Ui_user_form()
    ui.setupUi(user_form)
    user_form.show()
    sys.exit(app.exec_())
